### ISSUE TITLE
Add audio to the recorder (Enquiry not issue)

### ISSUE THREAD

**Issue by osinnowo** [amosyuen/FFmpegVideoRecorder#10]
I'm actually impressed by this library, really nice.
 
I've been looking for library (or a way) to record video and play song for the audio, want to build and App just like VideoFX, [https://play.google.com/store/apps/details?id=com.videofx](https://play.google.com/store/apps/details?id=com.videofx)

Any suggestion or guide. 

Thanks

**Comment by amosyuen** [comment]
Recording just video is pretty easy, you can just use MediaRecorder to do that. As for splicing the audio and video together, my guess is it's possible to step through the frames and record them together using FFMpeg somehow. Probably try to poke around how https://github.com/bytedeco/javacv/blob/master/src/main/java/org/bytedeco/javacv/FFmpegFrameRecorder.java handles recording.
