### ISSUE TITLE
Cobining 2 videos in one

### ISSUE THREAD

**Issue by husseinAYehya** [amosyuen/FFmpegVideoRecorder#13]
hi dear,

please can u post the code of combining 2 videos in 1 video

**Comment by amosyuen** [comment]
Code is already posted. Most of it is in https://github.com/amosyuen/FFmpegVideoRecorder/blob/master/ffmpeg-video-recorder/src/main/java/com/amosyuen/videorecorder/recorder/VideoTransformerTask.java
