### ISSUE TITLE
can't save recorded video

### ISSUE THREAD

**Issue by ksatalsin** [amosyuen/FFmpegVideoRecorder#2]
Samsung galaxy s6 edge (6.1)

Rejecting re-init on previously-failed class java.lang.Class<org.bytedeco.javacpp.avutil>

AndroidRuntime: FATAL EXCEPTION: AsyncTask...

**Comment by amosyuen** [comment]
Looks like the native libraries aren't being found. This likely is related to your other post: https://github.com/amosyuen/FFmpegVideoRecorder/issues/1
