### ISSUE TITLE
xiao mi 4LTE 6.0.1  crash

### ISSUE THREAD

**Issue by QPymac** [amosyuen/FFmpegVideoRecorder#3]
![image](https://cloud.githubusercontent.com/assets/17897163/21468009/a8f43e4a-ca3b-11e6-9674-9ab33ba12da8.png)

**Comment by amosyuen** [comment]
Is this running the included demo by itself? Not as part of another project?

Looks like native libraries aren't getting installed properly. Could you install https://play.google.com/store/apps/details?id=com.xh.nativelibsmonitor.app and lookup the demo and post the info there?

**Comment by QPymac** [comment]
yes,i run zhe demo FFmpegVideoRecorder-1.0.2
![image](https://cloud.githubusercontent.com/assets/17897163/21469392/0246c276-ca85-11e6-940e-fccf71e03912.png)
![image](https://cloud.githubusercontent.com/assets/17897163/21469395/24a47bd8-ca85-11e6-97f2-490a532c4262.png)

**Comment by amosyuen** [comment]
Huh, looks like the native libraries are installed correctly. I tried removing all the armv7 libraries, and verified the demo works with armv5 on my Samsung S5 phone. So that verifies that the armv5 libraries work.

When you said you were running v1.0.2, did you mean you were using demo v1.2.0? Or did you mean that you are using v1.0.2 of the library? Note: the demo and library have different version numbers. The library is now v1.0.5, so if you're using the old library please update and try again.

**Comment by QPymac** [comment]
I'm download the last version(branch-master) demo and use another phone(meizu android5.1)  has the same Problem

**Comment by amosyuen** [comment]
Hmm, I'm not really sure what's going on since it shows that the native libraries were installed.

Could you follow the steps in http://android.wonderhowto.com/how-to/android-basics-see-what-kind-processor-you-have-arm-arm64-x86-0168051/ and get a screenshot of the processor architecture details?

**Comment by QPymac** [comment]
![image](https://cloud.githubusercontent.com/assets/17897163/21474500/2192eb10-cb5b-11e6-8257-a8963206f301.png)
![image](https://cloud.githubusercontent.com/assets/17897163/21474513/2f9e4bb4-cb5b-11e6-9adb-1267b3744d52.png)
![image](https://cloud.githubusercontent.com/assets/17897163/21474515/364a62c2-cb5b-11e6-8365-98928758c556.png)
com.inkwired.droidinfo.apk install mi 4LTE crash also ......

**Comment by amosyuen** [comment]
Huh, interestingly seems like the kernel architecture is arm v7, but the arm v5 libraries were installed instead...

This is a shot in the dark, but perhaps we can try forcing the arm v7 libraries to install. Try deleting all the files in ffmpeg-video-recorder/src/main/jniLibs/armeabi and ffmpeg-video-recorder/src/main/jniLibs/x86, so leaving only the aremabi-v7a folder. Then try building and launching the demo. Also perhaps using the native libs monitor app, verify that the v7 was installed.

**Comment by QPymac** [comment]
I'm fix code like 
![image](https://cloud.githubusercontent.com/assets/17897163/21513084/5db3b580-ccef-11e6-9a1f-df9bc165bb86.png)
now is worked!

**Comment by amosyuen** [comment]
Added suggested fix in https://github.com/amosyuen/FFmpegVideoRecorder/commit/5600dc2a243ad4bbb8427abfc72a4a1de44cd2b6
