### ISSUE TITLE
Video frame rate is not what I set

### ISSUE THREAD

**Issue by HamAndBean** [amosyuen/FFmpegVideoRecorder#4]
video frames is not what I set.I set the video frames 30,when I get the video, it shows the average frame is 17.329 fps ,the max frame is 30 fps,the min frame is 1 fps?

**Comment by amosyuen** [comment]
The min and max frame rate depend on the camera. But another problem is it seems that using FFmpeg to directly capture camera images and record it in real time isn't very performant, so sometimes we miss some frames. I'm working on a v2 that uses MediaRecorder to record and then FFmpeg to transform the images. It' not quite ready yet, but it definitely fixes the frame rate problem.

**Comment by amosyuen** [comment]
I just released v2.0.0. Please take a look.
